apiVersion: v1
kind: Secret
metadata:
  name: taskai-secrets
  namespace: taskai
type: Opaque
data:
  MONGO_URI: BASE64_MONGO_URI
  JWT_SECRET: BASE64_JWT_SECRET
  REDIS_HOST: cmVkaXMtc2VydmljZQ==
  REDIS_PORT: NjM3OQ==
