apiVersion: v1
kind: Secret

metadata:
  name: taskai-secrets
  namespace: taskai

type: Opaque

stringData:
  MONGO_URI: "mongodb://ashishjhaaa1433_db_user:Rjfvr2UBz7RI9fNS@ac-wbnf8gi-shard-00-00.cohrdja.mongodb.net:27017,ac-wbnf8gi-shard-00-01.cohrdja.mongodb.net:27017,ac-wbnf8gi-shard-00-02.cohrdja.mongodb.net:27017/ai-task-platform?ssl=true&replicaSet=atlas-1o4sa7-shard-0&authSource=admin&retryWrites=true&w=majority"

  JWT_SECRET: "supersecretjwt"

  REDIS_HOST: "redis-service"

  REDIS_PORT: "6379"

  NODE_ENV: "production"

  PORT: "5000"